server:
  port: 8004
 
spring:
  application:
    name: orderService
    
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/order_system
   username: root
   password: 123456
    
eureka:
  instance:
    instance-id: orderService
    appname: ${spring.application.name}
  client: 
    service-url: 
      defaultZone: http://admin:123456@127.0.0.1:8888/eureka/

mybatis:
  typeAliasesPackage: com.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  



  